### Подготовил: Еюбоглу Тимур
### Ст. билет: 1032224357
### Группа: НПИбд-01-22

### Кортежи

#### Примеры кортежей:

In [3]:
# пустой кортеж:
()

()

In [4]:
# кортеж из элементов типа String:
favoritelang = ("Python","Julia","R")

("Python", "Julia", "R")

In [5]:
# кортеж из целых чисел:
x1 = (1, 2, 3)


(1, 2, 3)

In [6]:
# кортеж из элементов разных типов:
x2 = (1, 2.0, "tmp")


(1, 2.0, "tmp")

In [7]:
# именованный кортеж:
x3 = (a=2, b=1+2)

(a = 2, b = 3)

#### Примеры операций над кортежами:

In [8]:
# длина кортежа x2:
length(x2)

3

In [9]:
# обратиться к элементам кортежа x2:
x2[1], x2[2], x2[3]


(1, 2.0, "tmp")

In [10]:
# произвести какую-либо операцию (сложение)
# с вторым и третьим элементами кортежа x1:
с = x1[2] + x1[3]

5

In [11]:
# обращение к элементам именованного кортежа x3:
x3.a, x3.b, x3[2]

(2, 3, 3)

In [12]:
# проверка вхождения элементов tmp и 0 в кортеж x2
# (два способа обращения к методу in()):
in("tmp", x2), 0 in x2

(true, false)

### Словари

#### Примеры словарей и операций над ними:

In [13]:
# создать словарь с именем phonebook:
phonebook = Dict("Иванов И.И." => ("867-5309","333-5544"),"Бухгалтерия" => "555-2368")

Dict{String, Any} with 2 entries:
  "Бухгалтерия" => "555-2368"
  "Иванов И.И." => ("867-5309", "333-5544")

In [14]:
# вывести ключи словаря:
keys(phonebook)

KeySet for a Dict{String, Any} with 2 entries. Keys:
  "Бухгалтерия"
  "Иванов И.И."

In [15]:
# вывести значения элементов словаря:
values(phonebook)

ValueIterator for a Dict{String, Any} with 2 entries. Values:
  "555-2368"
  ("867-5309", "333-5544")

In [16]:
# вывести заданные в словаре пары "ключ - значение":
pairs(phonebook)

Dict{String, Any} with 2 entries:
  "Бухгалтерия" => "555-2368"
  "Иванов И.И." => ("867-5309", "333-5544")

In [17]:
# проверка вхождения ключа в словарь:
haskey(phonebook, "Иванов И.И.")

true

In [18]:
# добавить элемент в словарь:
phonebook["Сидоров П.С."] = "555-3344"

"555-3344"

In [19]:
# удалить ключ и связанные с ним значения из словаря
pop!(phonebook, "Иванов И.И.")

("867-5309", "333-5544")

In [20]:
# Объединение словарей (функция merge()):
a = Dict("foo" => 0.0, "bar" => 42.0);
b = Dict("baz" => 17, "bar" => 13.0);
merge(a, b), merge(b,a)

(Dict{String, Real}("bar" => 13.0, "baz" => 17, "foo" => 0.0), Dict{String, Real}("bar" => 42.0, "baz" => 17, "foo" => 0.0))

### Множества

### Примеры множеств и операций над ними:

In [21]:
# создать множество из четырёх целочисленных значений:
A = Set([1, 3, 4, 5])

Set{Int64} with 4 elements:
  5
  4
  3
  1

In [22]:
# создать множество из 11 символьных значений:
B = Set("abrakadabra")

Set{Char} with 5 elements:
  'a'
  'd'
  'r'
  'k'
  'b'

In [23]:
# проверка эквивалентности двух множеств:
S1 = Set([1,2]);
S2 = Set([3,4]);
issetequal(S1,S2)

false

In [24]:
S3 = Set([1,2,2,3,1,2,3,2,1]);
S4 = Set([2,3,1]);
issetequal(S3,S4)

true

In [25]:
# объединение множеств:
C=union(S1,S2)

Set{Int64} with 4 elements:
  4
  2
  3
  1

In [26]:
# пересечение множеств:
D = intersect(S1,S3)

Set{Int64} with 2 elements:
  2
  1

In [27]:
# разность множеств:
E = setdiff(S3,S1)

Set{Int64} with 1 element:
  3

In [28]:
# проверка вхождения элементов одного множества в другое:
issubset(S1,S4)

true

In [29]:
# добавление элемента в множество:
push!(S4, 99)

Set{Int64} with 4 elements:
  2
  99
  3
  1

In [30]:
# удаление последнего элемента множества:
pop!(S4)

2

### Массивы

#### Примеры массивов:

In [31]:
# создание пустого массива с абстрактным типом:
empty_array_1 = []

Any[]

In [32]:
# создание пустого массива с конкретным типом:
empty_array_2 = (Int64)[]
empty_array_3 = (Float64)[]

Float64[]

In [33]:
# вектор-столбец:
a = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [34]:
# вектор-строка:
b = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [35]:
# многомерные массивы (матрицы):
A = [[1, 2, 3] [4, 5, 6] [7, 8, 9]]
B = [[1 2 3]; [4 5 6]; [7 8 9]]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [36]:
# одномерный массив из 8 элементов (массив $1 \times 8$)
# со значениями, случайно распределёнными на интервале [0, 1):
c = rand(1,8)

1×8 Matrix{Float64}:
 0.39419  0.736679  0.194042  0.505685  …  0.511107  0.936202  0.198453

In [37]:
# многомерный массив $2 \times 3$ (2 строки, 3 столбца) элементов
# со значениями, случайно распределёнными на интервале [0, 1):
C = rand(2,3)

2×3 Matrix{Float64}:
 0.067948   0.0921951  0.612529
 0.0904894  0.448998   0.699659

In [38]:
# трёхмерный массив:
D = rand(4, 3, 2)

4×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.620908  0.496382  0.918964
 0.108811  0.208313  0.551724
 0.746312  0.107278  0.978613
 0.867313  0.436442  0.282603

[:, :, 2] =
 0.825435  0.991333   0.737221
 0.434437  0.0718408  0.954832
 0.962281  0.870374   0.0118612
 0.703507  0.0244738  0.252781

#### Примеры массивов, заданных некоторыми функциями через включение:

In [39]:
# массив из квадратных корней всех целых чисел от 1 до 10:
roots = [sqrt(i) for i in 1:10]

10-element Vector{Float64}:
 1.0
 1.4142135623730951
 1.7320508075688772
 2.0
 2.23606797749979
 2.449489742783178
 2.6457513110645907
 2.8284271247461903
 3.0
 3.1622776601683795

In [40]:
# массив с элементами вида 3*x^2,
# где x - нечётное число от 1 до 9 (включительно
ar_1 = [3*i^2 for i in 1:2:9]

5-element Vector{Int64}:
   3
  27
  75
 147
 243

In [41]:
# массив квадратов элементов, если квадрат не делится на 5 или 4:
ar_2=[i^2 for i=1:10 if (i^2%5!=0 && i^2%4!=0)]

4-element Vector{Int64}:
  1
  9
 49
 81

#### Некоторые операции для работы с массивами:

In [42]:
# одномерный массив из пяти единиц:
ones(5)

5-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0

In [43]:
# двумерный массив 2x3 из единиц:
ones(2,3)

2×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [44]:
# одномерный массив из 4 нулей:
zeros(4)

4-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0

In [45]:
# заполнить массив 3x2 цифрами 3.5
fill(3.5,(3,2))

3×2 Matrix{Float64}:
 3.5  3.5
 3.5  3.5
 3.5  3.5

In [46]:
# заполнение массива посредством функции repeat():
repeat([1,2],3,3)
repeat([1 2],3,3)

3×6 Matrix{Int64}:
 1  2  1  2  1  2
 1  2  1  2  1  2
 1  2  1  2  1  2

In [47]:
# преобразование одномерного массива из целых чисел от 1 до 12
# в двумерный массив 2x6
a = collect(1:12)
b = reshape(a,(2,6))

2×6 Matrix{Int64}:
 1  3  5  7   9  11
 2  4  6  8  10  12

In [48]:
# транспонирование
b'

6×2 adjoint(::Matrix{Int64}) with eltype Int64:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

In [49]:
# транспонирование
с = transpose(b)

6×2 transpose(::Matrix{Int64}) with eltype Int64:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

In [50]:
# массив 10x5 целых чисел в диапазоне [10, 20]:
ar = rand(10:20, 10, 5)

10×5 Matrix{Int64}:
 16  14  12  17  15
 18  13  15  20  16
 12  20  20  19  10
 16  17  14  18  12
 19  17  14  14  14
 15  11  20  14  15
 20  13  15  10  10
 15  18  10  18  16
 12  15  12  16  13
 10  10  20  12  17

In [51]:
# выбор всех значений строки в столбце 2:
ar[:, 2]

10-element Vector{Int64}:
 14
 13
 20
 17
 17
 11
 13
 18
 15
 10

In [52]:
# выбор всех значений в столбцах 2 и 5:
ar[:, [2, 5]]

10×2 Matrix{Int64}:
 14  15
 13  16
 20  10
 17  12
 17  14
 11  15
 13  10
 18  16
 15  13
 10  17

In [53]:
# все значения строк в столбцах 2, 3 и 4:
ar[:, 2:4]

10×3 Matrix{Int64}:
 14  12  17
 13  15  20
 20  20  19
 17  14  18
 17  14  14
 11  20  14
 13  15  10
 18  10  18
 15  12  16
 10  20  12

In [54]:
# значения в строках 2, 4, 6 и в столбцах 1 и 5:
ar[[2, 4, 6], [1, 5]]

3×2 Matrix{Int64}:
 18  16
 16  12
 15  15

In [55]:
# значения в строке 1 от столбца 3 до последнего столбца:
ar[1, 3:end]

3-element Vector{Int64}:
 12
 17
 15

In [56]:
# сортировка по столбцам:
sort(ar,dims=1)

10×5 Matrix{Int64}:
 10  10  10  10  10
 12  11  12  12  10
 12  13  12  14  12
 15  13  14  14  13
 15  14  14  16  14
 16  15  15  17  15
 16  17  15  18  15
 18  17  20  18  16
 19  18  20  19  16
 20  20  20  20  17

In [57]:
# сортировка по строкам:
sort(ar,dims=2)

10×5 Matrix{Int64}:
 12  14  15  16  17
 13  15  16  18  20
 10  12  19  20  20
 12  14  16  17  18
 14  14  14  17  19
 11  14  15  15  20
 10  10  13  15  20
 10  15  16  18  18
 12  12  13  15  16
 10  10  12  17  20

In [58]:
# поэлементное сравнение с числом
# (результат - массив логических значений):
ar .> 14

10×5 BitMatrix:
 1  0  0  1  1
 1  0  1  1  1
 0  1  1  1  0
 1  1  0  1  0
 1  1  0  0  0
 1  0  1  0  1
 1  0  1  0  0
 1  1  0  1  1
 0  1  0  1  0
 0  0  1  0  1

In [59]:
# возврат индексов элементов массива, удовлетворяющих условию:
findall(ar .> 14)

28-element Vector{CartesianIndex{2}}:
 CartesianIndex(1, 1)
 CartesianIndex(2, 1)
 CartesianIndex(4, 1)
 CartesianIndex(5, 1)
 CartesianIndex(6, 1)
 CartesianIndex(7, 1)
 CartesianIndex(8, 1)
 CartesianIndex(3, 2)
 CartesianIndex(4, 2)
 CartesianIndex(5, 2)
 CartesianIndex(8, 2)
 CartesianIndex(9, 2)
 CartesianIndex(2, 3)
 ⋮
 CartesianIndex(10, 3)
 CartesianIndex(1, 4)
 CartesianIndex(2, 4)
 CartesianIndex(3, 4)
 CartesianIndex(4, 4)
 CartesianIndex(8, 4)
 CartesianIndex(9, 4)
 CartesianIndex(1, 5)
 CartesianIndex(2, 5)
 CartesianIndex(6, 5)
 CartesianIndex(8, 5)
 CartesianIndex(10, 5)

### Самостоятельное выполнение

#### №1. Даны множества: 𝐴 = {0, 3, 4, 9}, 𝐵 = {1, 3, 4, 7}, 𝐶 = {0, 1, 2, 4, 7, 8, 9}. Найти 𝑃 = 𝐴 ∩ 𝐵 ∪ 𝐴 ∩ 𝐵 ∪ 𝐴 ∩ 𝐶 ∪ 𝐵 ∩ 𝐶.

In [60]:
A = Set([0, 3, 4, 9])
B = Set([1, 3, 4, 7])
C = Set([0, 1, 2, 4, 7, 8, 9])

P = union(intersect(A, B), intersect(A, C), intersect(B, C))
println(P)

Set([0, 4, 7, 9, 3, 1])


#### №2. Приведите свои примеры с выполнением операций над множествами элементов разных типов.

In [61]:
set1 = Set(["pineapple", "apple", "banana"])
set2 = Set(["banana" , "apple", "fejoa"])
intersection = intersect(set1, set2)
println(intersection)

Set(["banana", "apple"])


In [62]:
# Пример 2: множество чисел
set3 = Set([20, 30, 40])
set4 = Set([30, 40, 50])
difference = setdiff(set3, set4)
println(difference)

Set([20])


#### №3. Создайте разными способами:

##### 3.1) массив (1, 2, 3, … 𝑁 − 1, 𝑁 ), 𝑁 выберите больше 20

In [63]:
N = 25
array1 = collect(1:N)
println(array1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]


##### 3.2) массив (𝑁, 𝑁 − 1 … , 2, 1), 𝑁 выберите больше 20

In [64]:
array2 = collect(N:-1:1)
println(array2)

[25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


##### 3.3) массив (1, 2, 3, … , 𝑁 − 1, 𝑁, 𝑁 − 1, … , 2, 1), 𝑁 выберите больше 20

In [65]:
array3 = vcat(collect(1:N), collect(N-1:-1:1))
println(array3)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


##### 3.4) массив с именем tmp вида (4, 6, 3)

In [66]:
tmp = [4, 6, 3]
println(tmp)

[4, 6, 3]


##### 3.5) массив, в котором первый элемент массива tmp повторяется 10 раз

In [67]:
array4 = fill(tmp[1], 10)
println(array4)

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4]


##### 3.6) массив, в котором все элементы массива tmp повторяются 10 раз

In [68]:
array5 = repeat(tmp, 10)
println(array5)

[4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3]


##### 3.7) массив, в котором первый элемент массива tmp встречается 11 раз, второй элемент — 10 раз, третий элемент — 10 раз

In [69]:
array6 = vcat(fill(tmp[1], 11), fill(tmp[2], 10), fill(tmp[3], 10))
println(array6)

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]


##### 3.8) массив, в котором первый элемент массива tmp встречается 10 раз подряд, второй элемент — 20 раз подряд, третий элемент — 30 раз подряд

In [70]:
array7 = vcat(fill(tmp[1], 10), fill(tmp[2], 20), fill(tmp[3], 30))
println(array7)

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]


##### 3.9) массив из элементов вида 2^𝑡𝑚𝑝[𝑖], 𝑖 = 1, 2, 3, где элемент 2^𝑡𝑚𝑝[3] встречается 4 раза; посчитайте в полученном векторе, сколько раз встречается цифра 6, и выведите это значение на экран

In [71]:
# Задаем массив tmp
tmp = [4, 6, 3]

# Формируем массив: элемент 2^tmp[3] повторяется 4 раза
result_array = [2^tmp[i] for i in 1:3]
result_array = vcat(result_array, repeat([2^tmp[3]], 4))

# Преобразуем массив в строку для поиска цифры '6'
result_string = join(result_array, "")
count_6 = count(x -> x == '6', result_string)

# Выводим массив и количество цифр 6
println("Результирующий массив: ", result_array)
println("Количество цифры 6: ", count_6)

Результирующий массив: [16, 64, 8, 8, 8, 8, 8]
Количество цифры 6: 2


##### 3.10) вектор значений 𝑦 = 𝑒^𝑥 cos(𝑥) в точках 𝑥 = 3, 3.1, 3.2, … , 6, найдите среднее значение 𝑦

In [72]:
using Statistics

x = 3:0.1:6
y = [exp(x) * cos(x) for x in x]

println("Среднее значение y: ", mean(y))

Среднее значение y: 53.11374594642971


##### 3.11) вектор вида (𝑥^𝑖, 𝑦^𝑗), 𝑥 = 0.1, 𝑖 = 3, 6, 9, … , 36, 𝑦 = 0.2, 𝑗 = 1, 4, 7, … , 34

In [73]:
xi = collect(3:3:36) * 0.1
yj = collect(1:3:34) * 0.2
vector11 = [(x, y) for x in xi, y in yj]
println(vector11)

[(0.30000000000000004, 0.2) (0.30000000000000004, 0.8) (0.30000000000000004, 1.4000000000000001) (0.30000000000000004, 2.0) (0.30000000000000004, 2.6) (0.30000000000000004, 3.2) (0.30000000000000004, 3.8000000000000003) (0.30000000000000004, 4.4) (0.30000000000000004, 5.0) (0.30000000000000004, 5.6000000000000005) (0.30000000000000004, 6.2) (0.30000000000000004, 6.800000000000001); (0.6000000000000001, 0.2) (0.6000000000000001, 0.8) (0.6000000000000001, 1.4000000000000001) (0.6000000000000001, 2.0) (0.6000000000000001, 2.6) (0.6000000000000001, 3.2) (0.6000000000000001, 3.8000000000000003) (0.6000000000000001, 4.4) (0.6000000000000001, 5.0) (0.6000000000000001, 5.6000000000000005) (0.6000000000000001, 6.2) (0.6000000000000001, 6.800000000000001); (0.9, 0.2) (0.9, 0.8) (0.9, 1.4000000000000001) (0.9, 2.0) (0.9, 2.6) (0.9, 3.2) (0.9, 3.8000000000000003) (0.9, 4.4) (0.9, 5.0) (0.9, 5.6000000000000005) (0.9, 6.2) (0.9, 6.800000000000001); (1.2000000000000002, 0.2) (1.2000000000000002, 0.8)

##### 3.12) вектор с элементами (2^𝑖)/𝑖, 𝑖 = 1, 2, … , 𝑀, 𝑀 = 25


In [74]:
M = 25
vector12 = [2^i / i for i in 1:M]
println(vector12)

[2.0, 2.0, 2.6666666666666665, 4.0, 6.4, 10.666666666666666, 18.285714285714285, 32.0, 56.888888888888886, 102.4, 186.1818181818182, 341.3333333333333, 630.1538461538462, 1170.2857142857142, 2184.5333333333333, 4096.0, 7710.117647058823, 14563.555555555555, 27594.105263157893, 52428.8, 99864.38095238095, 190650.18181818182, 364722.0869565217, 699050.6666666666, 1.34217728e6]


##### 3.13) вектор вида (”fn1”, ”fn2”, …, ”fnN”), 𝑁 = 30

In [75]:
N = 30
vector13 = ["fn$i" for i in 1:N]
println(vector13)

["fn1", "fn2", "fn3", "fn4", "fn5", "fn6", "fn7", "fn8", "fn9", "fn10", "fn11", "fn12", "fn13", "fn14", "fn15", "fn16", "fn17", "fn18", "fn19", "fn20", "fn21", "fn22", "fn23", "fn24", "fn25", "fn26", "fn27", "fn28", "fn29", "fn30"]


##### 3.14) векторы 𝑥 = (𝑥1, 𝑥2, … , 𝑥𝑛) и 𝑦 = (𝑦1, 𝑦2, … , 𝑦𝑛) целочисленного типа длины 𝑛 = 250 как случайные выборки из совокупности 0, 1, …, 999; на его основе:

In [76]:
using Random

x = rand(0:999, 250)
y = rand(0:999, 250)

# Выбор y > 600
filtered_y = y[y .> 600]
println("Элементы y > 600: ", filtered_y)

# Соответствующие элементы x
corresponding_x = x[findall(y .> 600)]
println("Соответствующие x: ", corresponding_x)

# Различные операции
sum_exp = sum(exp.(-x[2:end] + x[1:end-1]) .+ 10)
println("Сумма: ", sum_exp)

# Уникальные элементы x
unique_x = unique(x)
println("Уникальные элементы x: ", unique_x)

Элементы y > 600: [608, 864, 987, 970, 934, 960, 927, 880, 915, 908, 949, 855, 817, 988, 726, 636, 708, 773, 904, 949, 707, 995, 872, 761, 852, 922, 773, 650, 878, 875, 763, 912, 760, 775, 908, 711, 824, 692, 771, 822, 622, 643, 760, 729, 627, 773, 839, 929, 702, 959, 976, 741, 832, 975, 820, 797, 712, 745, 838, 621, 933, 880, 647, 617, 985, 812, 865, 720, 813, 639, 990, 703, 777, 753, 943, 723, 637, 634, 703, 987, 736, 721, 894, 608, 661, 766, 753, 737, 950, 625, 663, 887, 879, 812, 816, 619, 836, 746, 942, 674, 950, 966, 657, 877, 949]
Соответствующие x: [114, 818, 536, 807, 65, 946, 208, 163, 822, 858, 960, 742, 429, 940, 71, 624, 382, 722, 658, 106, 740, 759, 717, 335, 23, 596, 804, 497, 313, 393, 197, 82, 319, 50, 526, 900, 327, 230, 426, 409, 110, 257, 712, 130, 33, 854, 262, 409, 461, 209, 879, 724, 773, 271, 469, 701, 322, 766, 423, 377, 314, 453, 122, 717, 476, 106, 131, 614, 174, 671, 789, 67, 449, 88, 508, 166, 211, 729, 324, 591, 947, 382, 851, 613, 478, 65, 953, 44, 809, 2

#### №4. Создайте массив squares, в котором будут храниться квадраты всех целых чисел от 1 до 100.

In [77]:
squares = [i^2 for i in 1:100]
println(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801, 10000]


#### 5. Подключите пакет Primes (функции для вычисления простых чисел). Сгенерируйте массив myprimes, в котором будут храниться первые 168 простых чисел. Определите 89-е наименьшее простое число. Получите срез массива с 89-го до 99-го элемента включительно, содержащий наименьшие простые числа.

In [78]:
using Primes

# Создаем список простых чисел до 1000 (или другого достаточно большого числа)
myprimes = primes(1000)

println("89-е простое число: ", myprimes[89])
println("Срез: ", myprimes[89:99])

89-е простое число: 461
Срез: [461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523]


#### 6. Вычислите выражения:

##### 6.1

In [79]:
sum1 = sum(i^3 + 4*i^2 for i in 10:100)
println(sum1)

26852735


##### 6.2

In [80]:
sum2 = sum((2^i / i + 3^i / i^2) for i in 1:25)
println(sum2)

2.1291704368143802e9


##### 6.3

In [81]:
sum3 = sum(prod(2:2n) / prod(3:2n+1) for n in 1:19)
println(sum3)

12.84175745993532
